#ifndef __server_user_token__h
#define __server_user_token__h

#include "common.h"

#define INCREASE_STEP 10

// set during inspection
struct server_user_token{
	uint32_t offset;// the offset of user token generated by the client
	//uint32_t * matched_idx_array;// matched idx with the signature fragment's encrypted token
	//uint32_t length;// length of the index array
	struct encrypted_token * matched_et;// set during inspection
	struct server_user_token * next;
	struct server_user_token * after_number_of_encrypted_tokens;
};
#endif
